# Generated by Django 4.0 on 2023-05-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('staff_info', models.TextField()),
                ('image', models.ImageField(upload_to='staff/images')),
                ('status', models.CharField(choices=[('AT', 'Active'), ('DS', 'Disable')], default='AT', max_length=2)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.occupation')),
            ],
        ),
    ]
