# Generated by Django 4.0 on 2023-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_info',
            field=models.TextField(max_length=250),
        ),
    ]
